name: cd

on:
  push:
    branches: [main]
jobs:
  steps: 
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build using script
      uses: scripts/buildprod.sh

